# Generated by Django 5.0.3 on 2024-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='conseils_personnalises',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='progression_quiz',
        ),
        migrations.AlterField(
            model_name='question',
            name='reponse_correcte',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulte',
            field=models.CharField(choices=[('Facile', 'Facile'), ('Moyen', 'Moyen'), ('Difficile', 'Difficile')], max_length=50),
        ),
    ]
