# Generated by Django 5.0.3 on 2024-03-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profilutilisateur_conseils_personnalises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConseilDeSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('choix_1', models.CharField(max_length=200)),
                ('choix_2', models.CharField(max_length=200)),
                ('choix_3', models.CharField(max_length=200)),
                ('choix_4', models.CharField(max_length=200)),
                ('reponse_correcte', models.IntegerField(choices=[(1, 'Choix 1'), (2, 'Choix 2'), (3, 'Choix 3'), (4, 'Choix 4')])),
            ],
        ),
        migrations.CreateModel(
            name='QuizzCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ConseilSecurite',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='user',
        ),
        migrations.RemoveField(
            model_name='progressionquiz',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='progressionquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='RessourceEducative',
        ),
        migrations.DeleteModel(
            name='StatistiquesUtilisation',
        ),
        migrations.AddField(
            model_name='questionquizz',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quizzcategory'),
        ),
        migrations.DeleteModel(
            name='ProfilUtilisateur',
        ),
        migrations.DeleteModel(
            name='ProgressionQuiz',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
