# Generated by Django 4.2.11 on 2024-03-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quiz_question_delete_questionquizz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/quiz_images'),
        ),
    ]
