# Generated by Django 4.2.11 on 2024-03-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, default='app/images/default_quiz_image.png', null=True, upload_to='app/images/quiz_images'),
        ),
    ]
