# Generated by Django 4.2.11 on 2024-03-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_quiz_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-date_modification']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
