# Generated by Django 4.2.11 on 2024-03-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_quiz_options_quiz_date_modification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre_loi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chapitre', models.IntegerField()),
                ('nom_chapitre', models.CharField(max_length=100)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titre_loi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_titre', models.IntegerField()),
                ('nom_titre', models.CharField(max_length=100)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, default='app/images/default_actualite_image.png', null=True, upload_to='app/images/actualite_images'),
        ),
        migrations.CreateModel(
            name='Loi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_article', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loi', to='app.chapitre_loi')),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loi', to='app.titre_loi')),
            ],
        ),
    ]
