# Generated by Django 4.2.11 on 2024-03-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_chapitre_loi_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('objet', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
