# Generated by Django 4.2.11 on 2024-03-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_messageutilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='RessourceEducative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='app/images/default_quiz_image.png', null=True, upload_to='app/images/ressources_images')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type_ressource', models.CharField(choices=[('article', 'Article'), ('video', 'Vidéo'), ('document', 'Document')], max_length=50)),
            ],
        ),
    ]
