# Generated by Django 4.2.11 on 2024-03-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ressourcepdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressourcepdf',
            name='lien',
        ),
        migrations.AddField(
            model_name='ressourcepdf',
            name='fichier',
            field=models.FileField(default=1, upload_to='app/pdfs'),
            preserve_default=False,
        ),
    ]
