# Generated by Django 4.2.11 on 2024-03-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='RessourceVideo',
        ),
        migrations.RenameField(
            model_name='ressourcevideo',
            old_name='title',
            new_name='titre',
        ),
    ]
