# Generated by Django 4.2.11 on 2024-03-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_video_ressourcevideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourcevideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='app/videos/'),
        ),
        migrations.AlterField(
            model_name='ressourcevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='app/videos/thumbnails/'),
        ),
    ]
