# Generated by Django 4.2.11 on 2024-03-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_ressourcevideo_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConseilSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
