# Generated by Django 4.2.11 on 2024-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_conseilsecurite_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conseilsecurite',
            old_name='description',
            new_name='contenu',
        ),
        migrations.AddField(
            model_name='conseilsecurite',
            name='categorie',
            field=models.CharField(choices=[('securite_comptes', 'Sécurisez vos comptes'), ('reseaux_sociaux', 'Réseaux sociaux'), ('reseaux_confidentialite', 'Réseaux et confidentialité'), ('gestion_mots_de_passe', 'Gestion des mots de passe')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conseilsecurite',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conseilsecurite',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
