# Generated by Django 4.2.11 on 2024-03-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_description_conseilsecurite_contenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseilsecurite',
            name='categorie',
            field=models.CharField(choices=[('Sécurisez vos comptes', 'Sécurisez vos comptes'), ('Réseaux sociaux', 'Réseaux sociaux'), ('Réseaux et confidentialité', 'Réseaux et confidentialité'), ('Gestion des mots de passe', 'Gestion des mots de passe')], max_length=50),
        ),
    ]
