# Generated by Django 4.2.11 on 2024-03-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_messagecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='conseil',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
