# Generated by Django 4.2.11 on 2024-03-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_question_conseil'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='app/future_partenaires/')),
                ('lien_site_web', models.URLField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('type_partenaire', models.CharField(choices=[('organisation', 'Organisation'), ('entreprise', 'Entreprise'), ('autre', 'Autre')], max_length=50)),
                ('secteur_activite', models.CharField(max_length=50)),
                ('date_prise_contact', models.DateField()),
                ('personne_en_charge', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('statut', models.CharField(choices=[('prospect', 'Prospect'), ('en_negociation', 'En négociation'), ('partenaire', 'Partenaire')], default='en_negociation', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='app/partenaires/')),
                ('lien_site_web', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
