# Generated by Django 4.2.11 on 2024-03-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_futurepartenaire_partenaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurepartenaire',
            name='date_prise_contact',
        ),
    ]
