# Generated by Django 4.2.11 on 2024-03-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_futurepartenaire_date_prise_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_violation', models.CharField(choices=[('fuite_donnees', 'Fuite de données personnelles'), ('acces_non_autorise', 'Accès non autorisé'), ('hameconnage', 'Hameçonnage (phishing)'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('description', models.TextField()),
                ('preuves', models.FileField(blank=True, null=True, upload_to='app/signalements/')),
                ('date_incident', models.DateTimeField(auto_now_add=True)),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée')], default='faible', max_length=10)),
                ('statut', models.CharField(choices=[('en_cours', "En cours d'investigation"), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='en_cours', max_length=10)),
            ],
        ),
    ]
