# Generated by Django 4.2.11 on 2024-03-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_signalementviolation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partenaire',
            old_name='logo',
            new_name='image',
        ),
    ]
