# Generated by Django 4.2.11 on 2024-03-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_logo_partenaire_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalementviolation',
            name='lien_site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futurepartenaire',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
